---
- name: Ensures traefik dir exist
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: docker
  with_items:
    - /var/www/traefik

- name: Adding traefik.toml file
  template:
    src: ../templates/traefik.toml.j2
    dest: /var/www/traefik/traefik.toml
    owner: ubuntu
    group: docker

- name: Adding docker-compose.yml file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: /var/www/traefik/docker-compose.yml
    owner: ubuntu
    group: docker

- name: Create the web network
  docker_network:
    name: web

- name: Stop traefik
  shell: docker-compose down
  args:
    chdir: /var/www/traefik

- name: Start traefik
  shell: docker-compose up -d
  args:
    chdir: /var/www/traefik
